# Generated by Django 4.2.20 on 2026-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_seats',
            field=models.IntegerField(default=50),
        ),
    ]
